### ISSUE TITLE
Suggestion - JuicyPotato

### ISSUE THREAD

**Issue by MidnightSeer** [itm4n/PrivescCheck#1]
Great script!  We use this for OSCP.  Would suggest you add the checks for the JuicyPotato COM technique?

https://github.com/ohpe/juicy-potato

**Comment by itm4n** [comment]
The purpose of JuicyPotato is to get code execution as SYSTEM when you have either SeImpersonatePrivilege or SeAssignPrimaryTokenPrivilege, which is one of the first checks I implemented.
The use of a custom COM server is just one way of capturing NTLM authentication and transforming it into a token, that you can then use thanks to impersonation capabilities.
So, there is no particular check to implement here.
