### ISSUE TITLE
Add SeRelabelPrivilege to HighPotentialPrivileges

### ISSUE THREAD

**Issue by nurfed1** [itm4n/PrivescCheck#18]
Hi,

Even though it won't be useful very often, would it make sense to add  [SeRelabelPrivilege](https://www.tiraniddo.dev/2021/06/the-much-misunderstood.html) to the [HighPotentialPrivileges](https://github.com/itm4n/PrivescCheck/blob/d474ad6723a3b42eb198bc457cc9efeca81275e8/src/03_User.ps1#L167)?

**Comment by itm4n** [comment]
Hi,

Yeah, I already thought about adding this privilege after reading JF's blog post.
But I didn't really know what to do with this one as it is only

**Comment by nurfed1** [comment]
From my testing it seems that any user can have the privilege, as long as the IntegrityLevel is High or above.

**Comment by itm4n** [comment]
Any user? Really? :thinking:

`IntegrityLevel` = `High` generally means admin (after UAC). I don't see this privilege. Even then, it would be irrelevant in the context of PrvescCheck.
`IntegrityLevel` = `System` means it's a service account. Have you ever found a service that doesn't run as `SYSTEM` and that has this privilege? :thinking: 

From JF's [blog post](https://www.tiraniddo.dev/2021/06/the-much-misunderstood.html):
> At any rate the only user that gets SeRelabelPrivilege by default is SYSTEM, which defaults to the System integrity level which is already the maximum allowed level so this behavior of the privilege seems pretty much moot. At any rate as it's a "God" privilege it will be disabled if the token has an integrity level less than High, so this lowering operation is going to be rarely useful.

**Comment by itm4n** [comment]
That being said, it could be the result of a custom config. A service account or an administrator could be granted this privilege manually.
That seems a very rare edge case but it's technically possible. :)

**Comment by nurfed1** [comment]
Yes, that's why I made this issue. 
Even if it isn't assigned by default, there's an edge case that it is assigned manually. :)

**Comment by itm4n** [comment]
Yes! Thank you! :thumbsup:
I updated the code. :)
