### ISSUE TITLE
BUG - script don't launch

### ISSUE THREAD

**Issue by b4b857f6ee** [itm4n/PrivescCheck#2]
Hello,

Maybe i miss something but i can't get it.

Windows 10 PRO 1909

![image](https://user-images.githubusercontent.com/36012515/88273565-a9af5b80-ccda-11ea-822a-b7469d4eddea.png)

**Comment by b4b857f6ee** [comment]
Ok i found it i guess but i can see nothing :/

![image](https://user-images.githubusercontent.com/36012515/88274062-69041200-ccdb-11ea-83b5-a7bc709fe0da.png)

**Comment by b4b857f6ee** [comment]
Ok cmd command work i get output but not in powershell

This command work : powershell -ep bypass -c ". .\Invoke-PrivescCheck.ps1; Invoke-PrivescCheck | Tee-Object result.txt"

**Comment by itm4n** [comment]
https://blog.truesec.com/2019/06/07/powershell-dot-sourcing/
