### ISSUE TITLE
Simplify execution

### ISSUE THREAD

**Issue by mhupfauer** [itm4n/PrivescCheck#22]
This can be easily run by a one-liner:
```powershell
IEX([Net.Webclient]::new().DownloadString("https://raw.githubusercontent.com/itm4n/PrivescCheck/master/PrivescCheck.ps1"));Invoke-PrivescCheck
```
Maybe consider adding this to the README.md

**Comment by itm4n** [comment]
The fact that I didn't include such a one-liner in the README is intentional.
