### ISSUE TITLE
Convert-To-XML error due to invalid character

### ISSUE THREAD

**Issue by mpgn** [itm4n/PrivescCheck#24]
Hello

I have an issue when exporting the file using XML (only xml is buggy)

![image](https://user-images.githubusercontent.com/5891788/130051656-2eef8c37-042b-4d5a-afdd-9ad5b939e190.png)

Tested on Windows server 2016 (1607), PSversion 5.1

I can provide more info if needed :)

**Comment by itm4n** [comment]
Hi!

One would expect that `ConvertTo-Xml` properly handles and escapes invalid characters, but it does not as it turns out...

```console
PS C:\> [char]0x00  | ConvertTo-Xml
ConvertTo-Xml : '.', hexadecimal value 0x00, is an invalid character.
At line:1 char:15
+ [char]0x00  | ConvertTo-Xml
+               ~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertTo-Xml], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertToXmlCommand

PS C:\> [char]0x01  | ConvertTo-Xml
ConvertTo-Xml : '☺', hexadecimal value 0x01, is an invalid character.
At line:1 char:15
+ [char]0x01  | ConvertTo-Xml
+               ~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertTo-Xml], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertToXmlCommand

PS C:\> [char]0x02  | ConvertTo-Xml
ConvertTo-Xml : '☻', hexadecimal value 0x02, is an invalid character.
At line:1 char:15
+ [char]0x02  | ConvertTo-Xml
+               ~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertTo-Xml], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertToXmlCommand

PS C:\> [char]0x41  | ConvertTo-Xml

xml                            Objects
---                            -------
version="1.0" encoding="utf-8" Objects
```

I'll have to add a function for sanitizing the output before exporting to XML.

**Comment by itm4n** [comment]
Before converting the result to XML, I now strip all the potentially invalid XML characters from the `ResultRawString` member.
I found a very efficient way to do so on [StackOverflow](https://stackoverflow.com/questions/45706565/how-to-remove-special-bad-characters-from-xml-using-powershell). :slightly_smiling_face: 

Could you test again in the same conditions and tell me if it's ok?

**Comment by mpgn** [comment]
Yep, fixed ! I let you the satisfaction of closing the issue :)

**Comment by mpgn** [comment]
(also thx for the beautiful color, much better ! )

**Comment by itm4n** [comment]
Thanks for the confirmation! :+1:
