### ISSUE TITLE
Specified cast is not valid

### ISSUE THREAD

**Issue by exploide** [itm4n/PrivescCheck#40]
I got some of the following errors on a Microsoft Windows Server 2019 Datacenter.

```
Specified cast is not valid.
At line:1077 char:17
+             if (($ServiceItem.Type -band $TypeMask) -gt 0) {
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], InvalidCastException
    + FullyQualifiedErrorId : System.InvalidCastException
```

This happens during multiple checks:

- SERVICES > Non-default Services
- SERVICES > Registry Permissions
- SERVICES > Binary Permissions
- SERVICES > Unquoted Path (info)
- SERVICES > Unquoted Path
- CONFIG > Point and Print

Running as admin doesn't change this. I tried adding `-Verbose` but no interesting information was shown to narrow down the issue.

Does this make sense for you? I probably have access to this particular system for only  one day. So if this isn't enough information, we may close this until it is clearly reproducible. But feel free to tell me which information might be helpful.

**Comment by itm4n** [comment]
Does the error occur only once (or just a couple of times) during each check, or do you get a long list of errors?
In the first case, there is probably an issue with a specific service that has an unrecognized (or null) type.
In the second case, well, this would be a bit more problematic... :/

**Comment by exploide** [comment]
I needed to supply 3 as the filter level value, and now it hit something:

```
VERBOSE: WindowsAzureTelemetryService
```

**Comment by itm4n** [comment]
Nice, thank you.
Yes, I forgot about the filter level, sorry.

Is it possible to get the service's detail from the registry?
The path should be `HKLM\SYSTEM\CurrentControlSet\Services\WindowsAzureTelemetryService`.

**Comment by exploide** [comment]
My work day is over now, but I might get a chance to access the system on Monday again. I'll try to collect the information.

**Comment by exploide** [comment]
It seems there aren't many registry entries within that service. This is all:

![telemetry-service-registry](https://user-images.githubusercontent.com/5670236/203021070-01662f9c-8bba-4c8e-aee4-54d91ee17fda.png)

**Comment by itm4n** [comment]
Ok, I see....
All the usual service settings are missing, so the Type is null, hence the cast error. This was my initial guess.
It's really weird, first time I see this. :thinking:
Anyway, thank you very much for taking the time to check. :)
The fix will be pretty simple.

**Comment by itm4n** [comment]
Services without an explicit type are now ignored.
