### ISSUE TITLE
Get-HotFixList misses updates

### ISSUE THREAD

**Issue by v-p-b** [itm4n/PrivescCheck#52]
I ran the script on a Server 2022 system with KB5033118 installed. Since this update apparently doesn't create a registry key in the [expected format](https://github.com/itm4n/PrivescCheck/blob/2b0903952dc9cf1a9278734fd8e957951ba20a19/src/check/Updates.ps1#L68) Get-HotFixList misses this update.

As far as I can tell parsing update information from the registry is an unsupported hack, so I think it would make sense in the long term if the script parsed both the registry and Get-HotFix, and warn the user if Get-Hotfix shows an update not collected from the registry.

**Comment by itm4n** [comment]
You are making a good point. I already noticed this discrepancy between the official `Get-HotFix` and the data present in the registry.

Your proposition makes sense, but I might also just get rid of the custom registry parsing altogether.

Thanks for taking the time to report the issue. I'll see what I can do.

**Comment by itm4n** [comment]
Should be fixed with commit 373014d6a7fb8a90e4599fab196366e3d8563539.
