### ISSUE TITLE
LapsV2 is not being checked?

### ISSUE THREAD

**Issue by nurfed1** [itm4n/PrivescCheck#54]
Hey,

It looks like LAPSv2 is currently not being checked. 
I don't have time to make a PR right now, but I think a check could be added for the following locations:
## Intune
HKLM:\Software\Microsoft\Policies\LAPS
## GPO
 HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\LAPS
## Local 
HKLM:\Software\Microsoft\Windows\CurrentVersion\LAPS

**Comment by itm4n** [comment]
Fixed with commit db7d1f7

**Comment by nurfed1** [comment]
Looks good!
Thanks.
