### ISSUE TITLE
List ASR rules

### ISSUE THREAD

**Issue by nodauf** [itm4n/PrivescCheck#57]
Hi,

It would interesting if PrivescCheck was able to detect whether ASR is configured or not, and if there is a misconfiguration among the ASR rules (cf. [win10-asr-get.ps1](https://github.com/directorcia/Office365/blob/master/win10-asr-get.ps1)).

Below an example of the script's output:
![image](https://github.com/itm4n/PrivescCheck/assets/7670696/b5c133c5-9bd8-4bbc-8656-2f77d83b72c2)

**Comment by itm4n** [comment]
Good idea! Thanks for the suggestion.

**Comment by itm4n** [comment]
Added with commit f106e7b
