### ISSUE TITLE
Bug in Find-SccmCacheFileCredentials?

### ISSUE THREAD

**Issue by nurfed1** [itm4n/PrivescCheck#58]
Hi,

Is the throw at line 725 intended? 

https://github.com/itm4n/PrivescCheck/blob/7d384bf88f12bc60ac9195936dcf6f5c60bd9559/src/helper/CredentialHelpers.ps1#L638-L730

It seems to be crashing the script when Get-SccmCacheFiles return $null.

![image](https://github.com/itm4n/PrivescCheck/assets/8027846/49670d9a-2c78-4d0b-8b4a-f316ca3d98d1)

**Comment by itm4n** [comment]
I pushed a quick fix with commit f4eb074, could you test again?

**Comment by nurfed1** [comment]
Yeah, that seems to work :) 
Thanks
