### ISSUE TITLE
Detect Defender exclusions rules and ASR rules

### ISSUE THREAD

**Issue by nodauf** [itm4n/PrivescCheck#59]
From this [tweet](https://x.com/VakninHai/status/1796628601535652289/photo/) it is possible to enumerate Windows Defender's exclusions by listing the event ID 5007.
For example, whitelisting cmd.exe generates the following event 
![image](https://github.com/itm4n/PrivescCheck/assets/7670696/b2fed5bc-5875-45d4-ad7a-ec07e56fc6c2)
The tool https://github.com/0xsp-SRD/MDE_Enum already implement this finding and also enumerates the event ID 1121 to retrieve the ASR rules that have matched.

**Comment by itm4n** [comment]
Added with commit 2a163c36e68ee61ae082d412a9b5039625e5daa0 (exclusions only, see issue #57 for ASR rules).
