### ISSUE TITLE
Check for DisableLUAInRepair

### ISSUE THREAD

**Issue by Acebond** [itm4n/PrivescCheck#60]
Based on the new MSI privilege escalation blog https://sec-consult.com/blog/detail/msi-installer-repair-to-system-a-detailed-journey/ MS have added the new registry key `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Installer\DisableLUAInRepair` which when set to 1 makes the system use the original insecure behavior.

Also mentioned here: https://support.microsoft.com/en-au/topic/september-10-2024-kb5043055-os-build-25398-1128-41329f96-f641-4ce0-8472-faa78cc6fb5b

I think PrivescCheck should check for that registry key being set to 1, and probably just link the person to the blog.

**Comment by itm4n** [comment]
Good idea! I'll do that. :+1:

**Comment by itm4n** [comment]
Implemented in commit bc30f598899fb24f5de8591260953ff4392d48e0.

**Comment by Acebond** [comment]
Love you work
